services:
  - type: web
    name: zorvyn-finance-api
    env: java
    rootDir: finance-api
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/finance-api-0.0.1-SNAPSHOT.jar --server.port=$PORT
